spring:
  application:
  name: hospital
  server:
    port: 3306

  jpa:
    show-sql: true
  datasource:
    url: "jdbc:mysql://localhost:3306/hospital"
    username : "root"
    password: "123456"
    driver-class-name : "com.mysql.cj.jdbc.Driver"
